// ─── Additional Hangman Word Categories ─────────────────────────────────────

export const EXTRA_CATEGORIES = [
  {
    id: 'kota', name: 'Kota Indonesia', icon: '🏙️',
    words: {
      easy: [
        { word: 'MEDAN', hint: 'Kota terbesar di Sumatera Utara' },
        { word: 'SOLO', hint: 'Kota budaya Jawa di tepian Bengawan' },
        { word: 'DEPOK', hint: 'Kota penyangga selatan Jakarta' },
        { word: 'BOGOR', hint: 'Kota hujan dengan kebun raya terkenal' },
        { word: 'AMBON', hint: 'Ibukota provinsi Maluku' },
        { word: 'BATAM', hint: 'Kota industri dekat Singapura' },
        { word: 'GARUT', hint: 'Kota domba dan dodol di Jawa Barat' },
        { word: 'JAMBI', hint: 'Ibukota provinsi di Sumatera tengah' },
        { word: 'PALU', hint: 'Kota yang pernah terkena tsunami 2018' },
        { word: 'TEGAL', hint: 'Kota teh dan warteg di Jawa Tengah' },
        { word: 'KUDUS', hint: 'Kota kretek dan menara di Jawa Tengah' },
        { word: 'TUBAN', hint: 'Kota pesisir utara Jawa Timur' },
        { word: 'NGAWI', hint: 'Kota di Jawa Timur dekat situs Trinil' },
        { word: 'DEMAK', hint: 'Kota kerajaan Islam pertama di Jawa' },
        { word: 'BLORA', hint: 'Kota minyak dan jati di Jawa Tengah' },
        { word: 'SUBANG', hint: 'Kota nanas di Jawa Barat' },
        { word: 'MADIUN', hint: 'Kota pecel dan kereta api Jawa Timur' },
        { word: 'GRESIK', hint: 'Kota industri semen Jawa Timur' },
        { word: 'JEMBER', hint: 'Kota tembakau di Jawa Timur' },
        { word: 'BLITAR', hint: 'Kota makam Bung Karno' },
        { word: 'MALANG', hint: 'Kota apel sejuk di Jawa Timur' },
        { word: 'BINJAI', hint: 'Kota rambutan di Sumatera Utara' },
      ],
      medium: [
        { word: 'BANDUNG', hint: 'Ibukota Jawa Barat yang sejuk' },
        { word: 'SEMARANG', hint: 'Ibukota Jawa Tengah dengan Lawang Sewu' },
        { word: 'MAKASSAR', hint: 'Kota terbesar di Sulawesi Selatan' },
        { word: 'MANADO', hint: 'Kota wisata laut di Sulawesi Utara' },
        { word: 'MATARAM', hint: 'Ibukota Nusa Tenggara Barat' },
        { word: 'DENPASAR', hint: 'Ibukota provinsi Bali' },
        { word: 'CIREBON', hint: 'Kota udang di pesisir Jawa Barat' },
        { word: 'KENDARI', hint: 'Ibukota Sulawesi Tenggara' },
        { word: 'SORONG', hint: 'Kota gerbang Raja Ampat' },
        { word: 'TERNATE', hint: 'Kota rempah di Maluku Utara' },
        { word: 'SURABAYA', hint: 'Kota pahlawan terbesar kedua Indonesia' },
        { word: 'JAYAPURA', hint: 'Ibukota provinsi Papua' },
        { word: 'BENGKULU', hint: 'Kota Rafflesia di pantai barat Sumatera' },
        { word: 'SIDOARJO', hint: 'Kota lumpur dan udang Jawa Timur' },
        { word: 'MAGELANG', hint: 'Kota dekat Borobudur' },
        { word: 'CILACAP', hint: 'Kota pelabuhan di selatan Jawa Tengah' },
        { word: 'TARAKAN', hint: 'Kota pulau di Kalimantan Utara' },
        { word: 'SERANG', hint: 'Ibukota provinsi Banten' },
        { word: 'KUPANG', hint: 'Ibukota Nusa Tenggara Timur' },
        { word: 'PADANG', hint: 'Kota rendang ibukota Sumatera Barat' },
      ],
      hard: [
        { word: 'PONTIANAK', hint: 'Kota khatulistiwa di Kalimantan Barat' },
        { word: 'PALEMBANG', hint: 'Kota pempek dan jembatan Ampera' },
        { word: 'BALIKPAPAN', hint: 'Kota minyak di Kalimantan Timur' },
        { word: 'YOGYAKARTA', hint: 'Kota pelajar dengan keraton dan Malioboro' },
        { word: 'BANJARMASIN', hint: 'Kota seribu sungai di Kalimantan Selatan' },
        { word: 'SAMARINDA', hint: 'Ibukota Kalimantan Timur' },
        { word: 'GORONTALO', hint: 'Kota sekaligus nama provinsi di Sulawesi' },
        { word: 'PEKANBARU', hint: 'Ibukota Riau yang berkembang pesat' },
        { word: 'TANGERANG', hint: 'Kota penyangga barat Jakarta' },
        { word: 'PURWOKERTO', hint: 'Kota mendoan di Jawa Tengah' },
        { word: 'TASIKMALAYA', hint: 'Kota bordir dan payung di Jawa Barat' },
        { word: 'PROBOLINGGO', hint: 'Pintu masuk Gunung Bromo' },
        { word: 'SURAKARTA', hint: 'Nama resmi kota Solo' },
        { word: 'BANYUWANGI', hint: 'Kota sunrise of Java paling timur Jawa' },
        { word: 'PEKALONGAN', hint: 'Kota batik di pesisir Jawa Tengah' },
        { word: 'MOJOKERTO', hint: 'Kota kerajaan Majapahit' },
        { word: 'PURBALINGGA', hint: 'Kota bulu mata dan owabong' },
        { word: 'TULUNGAGUNG', hint: 'Kota marmer di Jawa Timur' },
        { word: 'PANGKALPINANG', hint: 'Ibukota Bangka Belitung' },
        { word: 'BUKITTINGGI', hint: 'Kota wisata Ngarai Sianok Sumatera Barat' },
      ],
    },
  },
  {
    id: 'teknologi', name: 'Istilah Teknologi', icon: '💻',
    words: {
      easy: [
        { word: 'LAYAR', hint: 'Bagian perangkat yang menampilkan gambar' },
        { word: 'MOUSE', hint: 'Alat penunjuk komputer berbentuk tikus' },
        { word: 'KABEL', hint: 'Penghubung listrik atau data' },
        { word: 'WIFI', hint: 'Jaringan internet tanpa kabel' },
        { word: 'DATA', hint: 'Informasi digital yang diproses komputer' },
        { word: 'CHAT', hint: 'Percakapan teks secara daring' },
        { word: 'KODE', hint: 'Instruksi yang ditulis programmer' },
        { word: 'SITUS', hint: 'Halaman yang diakses lewat browser' },
        { word: 'VIRUS', hint: 'Program jahat yang merusak komputer' },
        { word: 'DRONE', hint: 'Pesawat tanpa awak yang dikendalikan remote' },
        { word: 'PIXEL', hint: 'Titik terkecil penyusun gambar digital' },
        { word: 'MODEM', hint: 'Alat penghubung internet dari provider' },
        { word: 'FLASH', hint: 'Media penyimpanan portabel USB' },
        { word: 'ROBOT', hint: 'Mesin otomatis yang meniru gerakan manusia' },
        { word: 'RADAR', hint: 'Sistem deteksi objek menggunakan gelombang' },
        { word: 'EMAIL', hint: 'Surat elektronik lewat internet' },
        { word: 'AUDIO', hint: 'Sinyal suara dalam format digital' },
        { word: 'VIDEO', hint: 'Rekaman gambar bergerak' },
        { word: 'FIBER', hint: 'Kabel optik untuk internet super cepat' },
        { word: 'LASER', hint: 'Sinar terfokus berenergi tinggi' },
        { word: 'RAM', hint: 'Memori sementara untuk menjalankan program' },
        { word: 'CPU', hint: 'Otak komputer yang memproses data' },
      ],
      medium: [
        { word: 'KOMPUTER', hint: 'Mesin elektronik pengolah data' },
        { word: 'INTERNET', hint: 'Jaringan global penghubung dunia' },
        { word: 'PRINTER', hint: 'Alat untuk mencetak dokumen' },
        { word: 'BROWSER', hint: 'Aplikasi untuk menjelajah web' },
        { word: 'HACKER', hint: 'Orang yang membobol sistem keamanan' },
        { word: 'SERVER', hint: 'Komputer pusat penyedia layanan jaringan' },
        { word: 'LAPTOP', hint: 'Komputer portabel yang bisa dilipat' },
        { word: 'MONITOR', hint: 'Layar tampilan komputer desktop' },
        { word: 'ROUTER', hint: 'Alat pengarah lalu lintas jaringan' },
        { word: 'WEBSITE', hint: 'Kumpulan halaman di world wide web' },
        { word: 'MEMORI', hint: 'Komponen penyimpan data di perangkat' },
        { word: 'SENSOR', hint: 'Komponen pendeteksi perubahan lingkungan' },
        { word: 'ANDROID', hint: 'Sistem operasi HP buatan Google' },
        { word: 'STARTUP', hint: 'Perusahaan teknologi baru yang inovatif' },
        { word: 'DIGITAL', hint: 'Berbasis angka biner nol dan satu' },
        { word: 'MALWARE', hint: 'Perangkat lunak berbahaya' },
        { word: 'TABLET', hint: 'Perangkat layar sentuh lebih besar dari HP' },
        { word: 'UPLOAD', hint: 'Mengunggah file ke internet' },
        { word: 'PODCAST', hint: 'Siaran audio yang bisa didengar kapan saja' },
        { word: 'GADGET', hint: 'Perangkat elektronik kecil dan canggih' },
      ],
      hard: [
        { word: 'ALGORITMA', hint: 'Langkah-langkah logis untuk menyelesaikan masalah' },
        { word: 'BLOCKCHAIN', hint: 'Teknologi rantai blok untuk mata uang kripto' },
        { word: 'ENKRIPSI', hint: 'Proses mengamankan data dengan kode rahasia' },
        { word: 'BANDWIDTH', hint: 'Kapasitas transfer data jaringan' },
        { word: 'PROCESSOR', hint: 'Chip utama yang mengeksekusi instruksi komputer' },
        { word: 'STREAMING', hint: 'Menonton atau mendengar konten secara langsung daring' },
        { word: 'BLUETOOTH', hint: 'Teknologi nirkabel jarak pendek' },
        { word: 'CYBERSECURITY', hint: 'Keamanan dunia maya dari serangan digital' },
        { word: 'ARTIFICIAL', hint: 'Kata depan kecerdasan buatan (__ Intelligence)' },
        { word: 'PERANGKAT', hint: 'Alat atau piranti keras maupun lunak' },
        { word: 'PROGRAMMING', hint: 'Aktivitas menulis kode program komputer' },
        { word: 'OPERATING', hint: 'Kata depan sistem operasi (__ System)' },
        { word: 'SMARTPHONE', hint: 'Telepon genggam pintar dengan banyak fitur' },
        { word: 'AUTHENTICATION', hint: 'Proses verifikasi identitas pengguna' },
        { word: 'CLOUD', hint: 'Penyimpanan dan komputasi lewat internet' },
        { word: 'DEBUGGING', hint: 'Proses mencari dan memperbaiki error program' },
        { word: 'FIREWALL', hint: 'Sistem keamanan yang menyaring lalu lintas jaringan' },
        { word: 'REPOSITORY', hint: 'Tempat penyimpanan kode sumber proyek' },
        { word: 'VIRTUALISASI', hint: 'Membuat versi virtual dari perangkat keras' },
        { word: 'FRAMEWORK', hint: 'Kerangka kerja untuk membangun aplikasi' },
      ],
    },
  },
  {
    id: 'makanan', name: 'Makanan & Minuman', icon: '🍽️',
    words: {
      easy: [
        { word: 'BAKSO', hint: 'Bola daging dalam kuah kaldu hangat' },
        { word: 'SATE', hint: 'Daging tusuk yang dibakar dengan bumbu kacang' },
        { word: 'NASI', hint: 'Makanan pokok utama orang Indonesia' },
        { word: 'SOTO', hint: 'Sup kuah kuning berisi ayam atau daging' },
        { word: 'PECEL', hint: 'Sayuran rebus dengan sambal kacang' },
        { word: 'RAWON', hint: 'Sup daging hitam khas Jawa Timur' },
        { word: 'BUBUR', hint: 'Nasi lembek yang dimasak dengan banyak air' },
        { word: 'OPOR', hint: 'Masakan santan putih khas Lebaran' },
        { word: 'GULAI', hint: 'Masakan bersantan kental bumbu kuning' },
        { word: 'TEMPE', hint: 'Makanan fermentasi kedelai khas Indonesia' },
        { word: 'KERAK', hint: '__ telor, jajanan khas Betawi' },
        { word: 'SERABI', hint: 'Kue tradisional dari tepung beras' },
        { word: 'LUMPIA', hint: 'Gulungan kulit tipis berisi sayuran' },
        { word: 'ONDE', hint: 'Bola goreng berwijen berisi kacang hijau' },
        { word: 'MENDOAN', hint: 'Tempe goreng tipis setengah matang' },
        { word: 'LONTONG', hint: 'Nasi yang dimasak dalam daun pisang' },
        { word: 'KETUPAT', hint: 'Nasi dalam anyaman janur kelapa' },
        { word: 'PAPEDA', hint: 'Makanan pokok sagu khas Papua' },
        { word: 'KOLAK', hint: 'Hidangan manis santan pisang dan ubi' },
        { word: 'WEDANG', hint: 'Minuman hangat tradisional Jawa' },
      ],
      medium: [
        { word: 'RENDANG', hint: 'Daging santan kering yang sangat terkenal di dunia' },
        { word: 'GUDEG', hint: 'Masakan nangka muda manis khas Yogyakarta' },
        { word: 'PEMPEK', hint: 'Makanan ikan dan sagu khas Palembang' },
        { word: 'GADO-GADO', hint: 'Salad sayur dengan saus kacang khas Jakarta' },
        { word: 'SIOMAY', hint: 'Dimsum ikan kukus dengan saus kacang' },
        { word: 'MARTABAK', hint: 'Kue tebal manis atau asin yang dilipat' },
        { word: 'BATAGOR', hint: 'Bakso tahu goreng khas Bandung' },
        { word: 'CILOK', hint: 'Bola aci yang digoreng atau direbus' },
        { word: 'CENDOL', hint: 'Minuman dingin santan dan gula merah' },
        { word: 'KLEPON', hint: 'Bola hijau pandan berisi gula merah leleh' },
        { word: 'PASTEL', hint: 'Pastri goreng berisi sayuran dan telur' },
        { word: 'KETOPRAK', hint: 'Lontong tahu tauge dengan bumbu kacang' },
        { word: 'GULAIIKAN', hint: 'Masakan ikan bersantan khas Padang' },
        { word: 'TONGSENG', hint: 'Masakan daging kambing bersantan dan kol' },
        { word: 'NASIGORENG', hint: 'Nasi yang ditumis dengan bumbu dan kecap' },
        { word: 'BAJIGUR', hint: 'Minuman hangat santan gula merah Sunda' },
        { word: 'BANDREK', hint: 'Minuman jahe hangat khas Jawa Barat' },
        { word: 'JAMU', hint: 'Minuman herbal tradisional dari rempah' },
        { word: 'DAWET', hint: 'Minuman cendol khas Banjarnegara' },
        { word: 'SEKOTENG', hint: 'Minuman jahe hangat dengan kacang dan roti' },
      ],
      hard: [
        { word: 'NASIPADANG', hint: 'Sajian nasi dengan lauk beraneka ragam dari Sumatera Barat' },
        { word: 'AYAMGEPREK', hint: 'Ayam goreng yang diulek dengan sambal pedas' },
        { word: 'SOPLANRANG', hint: 'Sup bening iga sapi dan jagung khas NTT' },
        { word: 'NASILIWET', hint: 'Nasi gurih yang dimasak dengan santan dan daun salam' },
        { word: 'MIEAYAM', hint: 'Mie kuah atau kering dengan topping daging ayam' },
        { word: 'NASIUDUK', hint: 'Nasi gurih santan khas Betawi' },
        { word: 'PECELAGEL', hint: 'Lauk ikan bumbu kacang khas Bali' },
        { word: 'AYAMBETUTU', hint: 'Ayam bumbu rempah dibungkus daun khas Bali' },
        { word: 'PAPEDAIKAN', hint: 'Papeda disajikan dengan ikan kuah kuning Papua' },
        { word: 'LAKSA', hint: 'Sup mie kuah santan rempah khas Melayu' },
        { word: 'SEBLAK', hint: 'Kerupuk basah pedas khas Bandung' },
        { word: 'BIKA', hint: '__ Ambon, kue sarang lebah khas Medan' },
        { word: 'SURABI', hint: 'Pancake tradisional Sunda dari tepung beras' },
        { word: 'TUMPENG', hint: 'Nasi kuning kerucut untuk perayaan' },
        { word: 'ASINAN', hint: 'Sayur atau buah dalam kuah asam pedas' },
        { word: 'OTAK', hint: '__ otak, makanan ikan panggang daun pisang' },
        { word: 'GEPUK', hint: 'Daging sapi geprek manis khas Sunda' },
        { word: 'KAREDOK', hint: 'Salad sayur mentah dengan bumbu kacang Sunda' },
        { word: 'EMPAL', hint: 'Daging sapi goreng manis khas Jawa' },
        { word: 'SERUNDENG', hint: 'Parutan kelapa sangrai yang gurih dan manis' },
      ],
    },
  },
]
